### ISSUE TITLE
Error: decode config json: unknown field "tag" using your Trojan gRPC SNI

### ISSUE THREAD

**Issue by essoojay** [malikshi/sing-box-examples#1]
hi, 

SFA  latest for 8/04/2023 

protocol:  Trojan gRPC SNI config.json example

error:  decode config json: unknown field "tag" 

please whats wrong? thanks

**Comment by malikshi** [comment]
post full config here, and hide credentials info

**Comment by essoojay** [comment]
> post full config here, and hide credentials info

I tried this:

{
      "tag": "proxy A",
      "type": "trojan",
      "server": "xxxxxxxx",       ---->> SNI IP
      "server_port": 443,
      "password": "xxxxxxx",
      "tls": {
        "enabled": true,
        "server_name": "XXXXXXXXX",   ------>>subdomain hostname
        "insecure": true,
        "utls": {
          "enabled": true,
          "fingerprint": "android"
        }
      },
      "transport": {
        "type": "grpc",
        "service_name": "xxxxx",
        "idle_timeout": "15s",
        "ping_timeout": "15s",
        "permit_without_stream": false
      },
      "multiplex": {
        "enabled": true,
        "protocol": "smux",
        "max_streams": 32
      }
}

**Comment by malikshi** [comment]
Full config
